# Generated by Django 4.0.4 on 2022-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikename', models.CharField(max_length=90)),
                ('manufacturer', models.CharField(max_length=90)),
                ('bike_model', models.PositiveIntegerField()),
                ('colour', models.CharField(max_length=55)),
                ('milage', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
